#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="btsync"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"
OMV_BTSYNC_DEFAULT_CONF="/etc/default/btsync"
OMV_BTSYNC_STORAGE_PATH="/var/lib/openmediavault-btsync"
OMV_BTSYNC_USER="btsync"

case "$1" in
    configure)
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "device_name" "BitTorrent Sync Server"
            omv_config_add_element "${SERVICE_XPATH}" "listening_port" "0"
            omv_config_add_element "${SERVICE_XPATH}" "use_upnp" "1"
            omv_config_add_element "${SERVICE_XPATH}" "lan_use_tcp" "0"
            omv_config_add_element "${SERVICE_XPATH}" "download_limit" "0"
            omv_config_add_element "${SERVICE_XPATH}" "upload_limit" "0"
            omv_config_add_element "${SERVICE_XPATH}" "shared_folders"

            omv_config_add_element "${SERVICE_XPATH}" "webui_enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "webui_port" "8888"
            omv_config_add_element "${SERVICE_XPATH}" "webui_username" "admin"
            omv_config_add_element "${SERVICE_XPATH}" "webui_password" "$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10)"
        fi

        # Set the default autostart instance to openmediavault
        echo "AUTOSTART=\"openmediavault\"" > ${OMV_BTSYNC_DEFAULT_CONF}

        # Fix permissions
        chown -R ${OMV_BTSYNC_USER}:${OMV_BTSYNC_USER} ${OMV_BTSYNC_STORAGE_PATH}
        find ${OMV_BTSYNC_STORAGE_PATH}/* -type d -exec chmod 750 {} +
        find ${OMV_BTSYNC_STORAGE_PATH}/* -type f -exec chmod 640 {} +

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
