#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        omv_config_delete "//services/btsync"
    ;;

    remove)
        OMV_BTSYNC_CONF=/etc/btsync/openmediavault.conf
        OMV_BTSYNC_DEFAULT_CONF=/etc/default/btsync

        /etc/init.d/btsync stop

        if [ -e "${OMV_BTSYNC_CONF}" ]; then
            /bin/rm "${OMV_BTSYNC_CONF}"
        fi

        if [ -e "${OMV_BTSYNC_DEFAULT_CONF}" ]; then
            /bin/rm "${OMV_BTSYNC_DEFAULT_CONF}"
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
