#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="btsync"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

OMV_BTSYNC_CONF="/etc/btsync/openmediavault.conf"
OMV_BTSYNC_DEFAULT_CONF="/etc/default/btsync"
OMV_BTSYNC_SERVICE_FILE="/etc/init.d/btsync"
OMV_BTSYNC_STORAGE_PATH="/var/lib/openmediavault-btsync"

case "$1" in
    purge)
        omv_config_delete ${SERVICE_XPATH}

        if [ -e "${OMV_BTSYNC_STORAGE_PATH}" ]; then
            rm -rf "${OMV_BTSYNC_STORAGE_PATH}"
        fi
    ;;

    remove)
        if [ -e "${OMV_BTSYNC_SERVICE_FILE}" ]; then
            ${OMV_BTSYNC_SERVICE_FILE} stop
        fi

        if [ -e "${OMV_BTSYNC_CONF}" ]; then
            rm "${OMV_BTSYNC_CONF}"
        fi

        if [ -e "${OMV_BTSYNC_DEFAULT_CONF}" ]; then
            rm "${OMV_BTSYNC_DEFAULT_CONF}"
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
